/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/MapPage`; params?: Router.UnknownInputParams; } | { pathname: `/MyAccountPage`; params?: Router.UnknownInputParams; } | { pathname: `/PetFormScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PetSitterServiceScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterPage`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterType`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `/components/DoublePressMarker`; params?: Router.UnknownInputParams; } | { pathname: `/components/PetSitterCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/useImagePicker`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/LoginPage`; params?: Router.UnknownOutputParams; } | { pathname: `/MapPage`; params?: Router.UnknownOutputParams; } | { pathname: `/MyAccountPage`; params?: Router.UnknownOutputParams; } | { pathname: `/PetFormScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/PetSitterServiceScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/RegisterPage`; params?: Router.UnknownOutputParams; } | { pathname: `/RegisterType`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownOutputParams; } | { pathname: `/components/DoublePressMarker`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PetSitterCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/useImagePicker`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/LoginPage${`?${string}` | `#${string}` | ''}` | `/MapPage${`?${string}` | `#${string}` | ''}` | `/MyAccountPage${`?${string}` | `#${string}` | ''}` | `/PetFormScreen${`?${string}` | `#${string}` | ''}` | `/PetSitterServiceScreen${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/RegisterPage${`?${string}` | `#${string}` | ''}` | `/RegisterType${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `${`?${string}` | `#${string}` | ''}` | `/components/DoublePressMarker${`?${string}` | `#${string}` | ''}` | `/components/PetSitterCard${`?${string}` | `#${string}` | ''}` | `/components/useImagePicker${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/LoginPage`; params?: Router.UnknownInputParams; } | { pathname: `/MapPage`; params?: Router.UnknownInputParams; } | { pathname: `/MyAccountPage`; params?: Router.UnknownInputParams; } | { pathname: `/PetFormScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PetSitterServiceScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterPage`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterType`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `/components/DoublePressMarker`; params?: Router.UnknownInputParams; } | { pathname: `/components/PetSitterCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/useImagePicker`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
